export const services = [
  {
    slug: 'business-assessment',
    label: 'Business Assessment',
    tagline: 'Get a complete picture of where your business actually stands.',
    shortDesc: 'Leave the engagement knowing exactly what\'s holding you back — and where to focus first.',
    pkg: 'Foundation',
    pkgSlug: 'package1',
    pkgColor: 'emerald',
    contactParam: 'business-assessment',
    icon: 'M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z',
    whoFor: [
      "You've been operating for a while but can't clearly identify what's holding you back",
      "You're preparing for a major change — new concept, expansion, or ownership transition",
      "You're experiencing inconsistent results and need an outside perspective to find the root cause",
    ],
    process: [
      { title: 'Discovery Call', desc: 'A 60-minute session to understand your business context, goals, and the specific challenges you want to address.' },
      { title: 'On-Site or Virtual Review', desc: 'We walk through your operations, financials, pipeline, staff structure, and tech stack in detail.' },
      { title: 'Analysis & Reporting', desc: 'Findings are compiled into a structured report — strengths, gaps, opportunities, and a clear priority order.' },
      { title: 'Results Walkthrough', desc: 'We present the report together, answer your questions, and align on what to tackle first.' },
    ],
    includes: [
      'Pipeline & revenue stream analysis',
      'Operations & workflow review',
      'Technology & systems audit',
      'Staffing structure evaluation',
      'Financial health snapshot',
      'Written report with prioritized recommendations',
    ],
    themes: ['Strategy', 'Diagnosis'],
    relatedSlugs: ['plan-of-action', 'performance-analytics'],
  },
  {
    slug: 'plan-of-action',
    label: 'Custom Plan of Action',
    tagline: 'Turn your assessment into a clear, executable roadmap.',
    shortDesc: 'A tailored strategic roadmap with milestones, KPIs, and a clear implementation timeline built for your business.',
    pkg: 'Foundation',
    pkgSlug: 'package1',
    pkgColor: 'emerald',
    contactParam: 'plan-of-action',
    icon: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01',
    whoFor: [
      "You know something needs to change but aren't sure where to start or in what order",
      "You've had plans before that never got executed — you need one built around your real constraints",
      "You're about to make a significant investment and want a data-backed strategy behind it",
    ],
    process: [
      { title: 'Assessment Review', desc: 'We start from your Business Assessment results (or conduct a condensed version) to anchor the plan in your real situation.' },
      { title: 'Priority Setting', desc: 'Together we rank opportunities by impact and feasibility, identifying the 3–5 moves that will drive the most change.' },
      { title: 'Roadmap Build', desc: 'We build a detailed action plan: milestones, owners, timelines, resource requirements, and success metrics for each initiative.' },
      { title: 'Handoff & Alignment', desc: 'The final plan is reviewed with your leadership team to ensure everyone is aligned and accountable from day one.' },
    ],
    includes: [
      'Priority-ranked initiative list',
      'Milestone & timeline framework',
      'Resource allocation guidance',
      'KPI definitions for each initiative',
      'Implementation checklist',
      'Leadership alignment session',
    ],
    themes: ['Strategy', 'Planning'],
    relatedSlugs: ['business-assessment', 'implementation-support'],
  },
  {
    slug: 'restaurant-maintenance',
    label: 'Restaurant Maintenance',
    tagline: 'Stop reacting to breakdowns. Start preventing them.',
    shortDesc: 'Preventive maintenance programs to eliminate equipment downtime and protect health compliance.',
    pkg: 'Foundation',
    pkgSlug: 'package1',
    pkgColor: 'emerald',
    contactParam: 'restaurant-maintenance',
    icon: 'M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z',
    whoFor: [
      "You've had unexpected equipment failures that shut down service and cost you thousands",
      "Your health inspection scores are inconsistent and you're not sure why",
      "You don't have a documented maintenance program and rely on vendors to tell you what needs fixing",
    ],
    process: [
      { title: 'Equipment & Facility Audit', desc: 'We walk every piece of equipment and facility system — cataloguing age, condition, service history, and risk level.' },
      { title: 'Compliance Review', desc: 'We cross-reference your current state against health code and safety requirements, flagging any gaps before an inspector does.' },
      { title: 'Maintenance Schedule Build', desc: 'A custom preventive maintenance calendar is built for your operation — daily, weekly, monthly, and annual tasks by equipment.' },
      { title: 'Vendor & Protocol Setup', desc: 'We help establish preferred vendor relationships and document cleaning protocols so your team executes consistently.' },
    ],
    includes: [
      'Full equipment & facility audit',
      'Health & safety compliance review',
      'Custom preventive maintenance calendar',
      'Deep cleaning protocol documentation',
      'Vendor & service contract guidance',
      'Staff maintenance responsibility assignments',
    ],
    themes: ['Operations', 'Compliance'],
    relatedSlugs: ['business-assessment', 'in-field-consultant'],
  },
  {
    slug: 'revenue-optimization',
    label: 'Revenue Optimization Strategy',
    tagline: 'Close the gaps between what you earn and what you could.',
    shortDesc: 'Close revenue leaks, sharpen pricing, and maximize performance across every revenue stream.',
    pkg: 'Growth',
    pkgSlug: 'package2',
    pkgColor: 'yellow',
    contactParam: 'revenue-optimization',
    icon: 'M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z',
    whoFor: [
      "Your revenue has plateaued but your costs keep climbing",
      "You suspect you're leaving money on the table but can't see exactly where",
      "You've added revenue streams (delivery, catering, events) but they're not performing as expected",
    ],
    process: [
      { title: 'Revenue Audit', desc: 'We map every revenue stream — dine-in, takeout, delivery, catering, events — and benchmark each against your cost structure.' },
      { title: 'Pricing Analysis', desc: 'We evaluate your current pricing strategy against food cost targets, competitor positioning, and guest price sensitivity.' },
      { title: 'Leak Identification', desc: 'We surface where revenue is being lost — from over-discounting and poor upsell habits to underperforming dayparts.' },
      { title: 'Strategy & Execution Plan', desc: 'A prioritized action plan targeting the highest-impact revenue opportunities with specific tactics and timelines.' },
    ],
    includes: [
      'Multi-stream revenue audit',
      'Pricing strategy analysis',
      'Upsell & average check review',
      'Daypart & peak hour analysis',
      'Delivery & off-premise performance review',
      'Revenue growth action plan',
    ],
    themes: ['Profitability', 'Revenue'],
    relatedSlugs: ['menu-engineering', 'performance-analytics'],
  },
  {
    slug: 'menu-engineering',
    label: 'Menu Engineering & Pricing',
    tagline: 'Your menu is your most powerful profit tool. Use it like one.',
    shortDesc: 'Restructure your menu around food cost, item performance, and margin — not guesswork.',
    pkg: 'Growth',
    pkgSlug: 'package2',
    pkgColor: 'yellow',
    contactParam: 'menu-engineering',
    icon: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2',
    whoFor: [
      "You have popular items that you later realized aren't actually profitable",
      "Your menu hasn't been reviewed in over a year and feels like it grew without a strategy",
      "You set prices by marking up food cost rather than by what the market will bear",
    ],
    process: [
      { title: 'Item-Level Cost Analysis', desc: 'We calculate true food cost for every item — accounting for portion size, waste, and prep labor — to get your real margin per dish.' },
      { title: 'Sales & Popularity Matrix', desc: 'We plot each item by profitability and popularity, identifying your Stars, Plowhorses, Puzzles, and Dogs.' },
      { title: 'Pricing Strategy', desc: 'We recommend pricing adjustments based on your cost targets, competitive landscape, and perceived value — not just a flat markup.' },
      { title: 'Menu Design Guidance', desc: 'We advise on layout, item placement, and description language to guide guests toward your highest-margin choices.' },
    ],
    includes: [
      'Item-level food cost calculation',
      'Profitability & popularity matrix',
      'Strategic pricing recommendations',
      'Menu layout & psychology guidance',
      'Underperformer removal recommendations',
      'Seasonal & limited-time opportunity analysis',
    ],
    themes: ['Profitability', 'Menu'],
    relatedSlugs: ['revenue-optimization', 'business-assessment'],
  },
  {
    slug: 'staff-training',
    label: 'Staff Training & Development',
    tagline: 'Build a team that performs consistently — without you watching.',
    shortDesc: 'Build structured programs that improve retention, consistency, and team performance.',
    pkg: 'Growth',
    pkgSlug: 'package2',
    pkgColor: 'yellow',
    contactParam: 'staff-training',
    icon: 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z',
    whoFor: [
      "You're constantly retraining the same things because nothing sticks",
      "Your turnover is high and you're not sure if it's a hiring or a culture problem",
      "Service quality varies wildly depending on who's working that day",
    ],
    process: [
      { title: 'Team & Culture Assessment', desc: 'We review your current hiring practices, onboarding process, role definitions, and team communication to find the gaps.' },
      { title: 'Training Program Design', desc: 'We build role-specific training guides covering service standards, procedures, and performance expectations for FOH and BOH.' },
      { title: 'Development Pathway', desc: 'We create a progression framework — entry, mid, and leadership levels — so your best people see a future at your restaurant.' },
      { title: 'Manager Coaching', desc: 'We work directly with your managers on how to deliver training consistently, handle performance issues, and retain key staff.' },
    ],
    includes: [
      'Hiring & onboarding process review',
      'Role-specific training guides',
      'Service & hospitality standards documentation',
      'Performance review framework',
      'Staff retention strategy',
      'Manager coaching sessions',
    ],
    themes: ['Staffing', 'Retention'],
    relatedSlugs: ['in-field-consultant', 'business-assessment'],
  },
  {
    slug: 'performance-analytics',
    label: 'Performance Analytics & Reporting',
    tagline: "Stop guessing. Know exactly what's working and what isn't.",
    shortDesc: 'Set up KPIs and dashboards so you always know where your business stands and what to act on.',
    pkg: 'Growth',
    pkgSlug: 'package2',
    pkgColor: 'yellow',
    contactParam: 'performance-analytics',
    icon: 'M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z',
    whoFor: [
      "You make decisions based on gut feel because you don't have reliable numbers to look at",
      "Your POS gives you data but you don't know what to do with it",
      "You review financials monthly (or less) and often feel blindsided by the results",
    ],
    process: [
      { title: 'Metrics Audit', desc: 'We review what data you currently track, how you track it, and where the blind spots are in your reporting.' },
      { title: 'KPI Framework Design', desc: "We define the 8–12 metrics that actually matter for your business — food cost, labor %, RevPASH, cover counts, average check, and more." },
      { title: 'Dashboard Setup', desc: 'We build or configure a simple reporting dashboard — weekly and monthly — that gives you the right numbers at a glance.' },
      { title: 'Cadence & Accountability', desc: "We set up a reporting rhythm and train your team on how to review results and translate them into weekly action priorities." },
    ],
    includes: [
      'Current metrics & reporting audit',
      'Custom KPI framework (8–12 core metrics)',
      'Weekly & monthly dashboard design',
      'Data source integration guidance',
      'Team reporting training',
      'Ongoing review cadence setup',
    ],
    themes: ['Data', 'Reporting'],
    relatedSlugs: ['revenue-optimization', 'monthly-reports'],
  },
  {
    slug: 'in-field-consultant',
    label: 'In-Field Consultant',
    tagline: "Strategy means nothing without execution. We're there for both.",
    shortDesc: 'A dedicated consultant on-site 3 days/week to drive implementation and hold your team accountable.',
    pkg: 'Enterprise',
    pkgSlug: 'package3',
    pkgColor: 'purple',
    contactParam: 'in-field-consultant',
    icon: 'M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z',
    whoFor: [
      "You've had great plans before that fell apart during execution",
      "Your team needs direct coaching and accountability — not just a report to follow",
      "You're making significant operational changes and can't afford for them to fail",
    ],
    process: [
      { title: 'Onboarding Week', desc: 'Your consultant spends the first week learning your operation, meeting the team, and establishing baseline metrics and priorities.' },
      { title: 'Weekly On-Site Presence', desc: '3 days per week on your floor — observing, coaching, running training sessions, and resolving issues in real time.' },
      { title: 'Weekly Reporting', desc: "Every week you receive a short briefing: what was worked on, what's improving, what still needs attention, and the focus for next week." },
      { title: 'Monthly Review', desc: 'A structured monthly review with ownership covering progress against the plan, adjusted priorities, and the path forward.' },
    ],
    includes: [
      '3 days/week on-site presence',
      'Real-time team coaching',
      'Weekly progress briefings',
      'Monthly owner review sessions',
      'Implementation of agreed action plan',
      '3-month minimum engagement (renewable)',
    ],
    themes: ['Execution', 'Hands-On'],
    relatedSlugs: ['implementation-support', 'staff-training'],
  },
  {
    slug: 'implementation-support',
    label: 'Implementation Support',
    tagline: 'The plan is done. Now make sure it actually gets executed.',
    shortDesc: 'Hands-on guidance through the execution phase to ensure changes actually stick across your operation.',
    pkg: 'Enterprise',
    pkgSlug: 'package3',
    pkgColor: 'purple',
    contactParam: 'implementation-support',
    icon: 'M13 10V3L4 14h7v7l9-11h-7z',
    whoFor: [
      "You have a solid plan but your team keeps defaulting back to old habits",
      "You're rolling out new systems or processes and need someone to manage the transition",
      "You want a consultant involved during execution without the full on-site commitment",
    ],
    process: [
      { title: 'Rollout Planning', desc: "We break your action plan into a phased rollout — sequencing changes to minimize disruption and maximize your team's ability to absorb them." },
      { title: 'Launch Support', desc: "We're available during the critical first weeks of each change, helping troubleshoot issues before they become ingrained problems." },
      { title: 'Change Management', desc: 'We coach managers on how to communicate changes, handle resistance, and build team buy-in for each initiative.' },
      { title: 'Checkpoint Reviews', desc: 'Regular structured check-ins to assess adoption, adjust the rollout timeline if needed, and confirm changes are sticking.' },
    ],
    includes: [
      'Phased rollout plan',
      'Launch week support (remote or on-site)',
      'Manager change management coaching',
      'Adoption tracking & checkpoints',
      'Issue resolution during execution',
      'Final implementation sign-off review',
    ],
    themes: ['Execution', 'Growth'],
    relatedSlugs: ['plan-of-action', 'in-field-consultant'],
  },
  {
    slug: 'monthly-reports',
    label: 'Monthly Progress Reports',
    tagline: 'Stay on track. Every month, without fail.',
    shortDesc: 'Never be surprised by your numbers again — every month, you know exactly where you stand and what to do next.',
    pkg: 'Enterprise',
    pkgSlug: 'package3',
    pkgColor: 'purple',
    contactParam: 'monthly-reports',
    icon: 'M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z',
    whoFor: [
      "You want ongoing visibility into your business without spending hours compiling numbers yourself",
      "You've worked with a consultant and want continued accountability after the engagement ends",
      "You need a structured reporting cadence to keep leadership aligned on priorities",
    ],
    process: [
      { title: 'Metrics Alignment', desc: 'We agree on the 8–12 KPIs that your monthly report will track — customized to what actually matters for your operation.' },
      { title: 'Data Collection Setup', desc: 'We establish a simple process for gathering the inputs needed each month — from your POS, P&L, and operational records.' },
      { title: 'Monthly Report Delivery', desc: 'Each month you receive a clean, one-page report: KPI dashboard, milestone status, key wins, open issues, and next-month focus.' },
      { title: 'Review Call', desc: 'A 30-minute call each month to walk through the report, discuss what the numbers mean, and align on priorities going forward.' },
    ],
    includes: [
      'Custom KPI dashboard',
      'Monthly written report',
      'Milestone & action item tracking',
      'Key wins & open issues summary',
      'Next-month priority recommendations',
      '30-minute monthly review call',
    ],
    themes: ['Reporting', 'Accountability'],
    relatedSlugs: ['performance-analytics', 'implementation-support'],
  },
]

export function getServiceBySlug(slug) {
  return services.find(s => s.slug === slug) || null
}

// Quiz scoring weights: each answer adds points toward service IDs
export const QUIZ_SCORING = {
  challenge: {
    revenue:        { 'revenue-optimization': 3, 'menu-engineering': 2, 'performance-analytics': 1 },
    staff:          { 'staff-training': 3, 'in-field-consultant': 2, 'business-assessment': 1 },
    menu:           { 'menu-engineering': 3, 'revenue-optimization': 2, 'business-assessment': 1 },
    maintenance:    { 'restaurant-maintenance': 3, 'business-assessment': 2, 'in-field-consultant': 1 },
    implementation: { 'in-field-consultant': 3, 'implementation-support': 2, 'plan-of-action': 1 },
    numbers:        { 'performance-analytics': 3, 'business-assessment': 2, 'revenue-optimization': 1 },
    expand:         { 'business-assessment': 3, 'plan-of-action': 2, 'revenue-optimization': 1 },
  },
  progress: {
    start:          { 'business-assessment': 3, 'plan-of-action': 2 },
    execute:        { 'implementation-support': 3, 'plan-of-action': 2 },
    accountability: { 'in-field-consultant': 3, 'monthly-reports': 2 },
  },
  involvement: {
    report:         { 'plan-of-action': 3, 'business-assessment': 2 },
    coaching:       { 'staff-training': 2, 'revenue-optimization': 2, 'menu-engineering': 1, 'performance-analytics': 1 },
    onsite:         { 'in-field-consultant': 3, 'implementation-support': 2 },
  },
}
